services:
  web:
    build: frontend
    command: npm run dev
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy
  api:
    build: api
    volumes:
      - ./api:/usr/src/api
    command: npx nodemon server.mjs
    ports:
      - "4001:4001"
    depends_on:
      db:
        condition: service_healthy
  redis:
    image: "redis:alpine"
    ports:
      - "4002:4002"
    container_name: redis

  db:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: movies_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - "4003:4003"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 4004:4004
volumes:
  pgdata:
