services:
  web:
    build:
      context: ./frontend

    command: npm run dev
    depends_on:
      redis:
        condition: service_started
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
