services:
  movie_conns_frontend:
    build: frontend

    command: npx next build; npm start
    environment:
      - NODE_ENV=development
    
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
  api:
    build: api
    volumes:
      - ./api:/usr/src/api
    command: node server.mjs
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "9004:9004"
      - "9005:9005"
  redis:
    image: "redis:alpine"
    container_name: redis

  db:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: movies_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_KEY}
volumes:
  pgdata:
