name: CI/CD Pipeline
on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main
jobs:
    build_images:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - name: build front and back + upload to dockerhub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          cd frontend
          docker build -t andrewb1234/frontend:ubuntu .
          docker push andrewb1234/frontend:ubuntu
          cd ../api
          docker build -t andrewb1234/backend:ubuntu .
          docker push andrewb1234/backend:ubuntu
          EOF
    deploy:
        runs-on: ubuntu-latest
        needs: build_images
        steps:
        - uses: actions/checkout@v4

        - name: Set up SSH
          uses: webfactory/ssh-agent@v0.8.0
          with:
            ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

        - name: Deploy to EC2
          run: |
            ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            mkdir -p ~/movie-conns
            cd ~/movie-conns
            git pull origin main
            docker compose pull
            docker compose up -d --build
            EOF